apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.api.replicaCount }}
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
        - name: api
          image: "{{ .Values.api.image.repository }}:{{ .Values.api.image.tag }}"
          imagePullPolicy: {{ .Values.api.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.api.service.port }}
          env:
            - name: NODE_ENV
              value: {{ .Values.api.env.NODE_ENV | quote }}
            - name: API_PORT
              value: {{ .Values.api.env.API_PORT | quote }}
            - name: CORS_ORIGINS
              value: {{ .Values.api.env.CORS_ORIGINS | quote }}
            - name: AWS_REGION
              value: {{ .Values.global.awsRegion | quote }}
            - name: SCHEDULER_SERVICE_URL
              value: {{ .Values.global.schedulerServiceUrl | quote }}
            - name: MONGODB_URI
              valueFrom:
                secretKeyRef:
                  name: relationship-reward-app-secrets
                  key: MONGODB_URI
            - name: JWT_ACCESS_SECRET
              valueFrom:
                secretKeyRef:
                  name: relationship-reward-app-secrets
                  key: JWT_ACCESS_SECRET
            - name: JWT_REFRESH_SECRET
              valueFrom:
                secretKeyRef:
                  name: relationship-reward-app-secrets
                  key: JWT_REFRESH_SECRET
            - name: REDIS_URL
              valueFrom:
                secretKeyRef:
                  name: relationship-reward-app-secrets
                  key: REDIS_URL
            - name: SES_FROM_EMAIL
              valueFrom:
                secretKeyRef:
                  name: relationship-reward-app-secrets
                  key: SES_FROM_EMAIL
          resources:
{{ toYaml .Values.api.resources | indent 12 }}
          readinessProbe:
            httpGet:
              path: /healthz
              port: {{ .Values.api.service.port }}
            initialDelaySeconds: 10
            periodSeconds: 10
