apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ .Values.secrets.externalSecretName }}
  namespace: {{ .Values.namespace }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: {{ .Values.secrets.storeRefName }}
  target:
    name: relationship-reward-app-secrets
    creationPolicy: Owner
  data:
    - secretKey: MONGODB_URI
      remoteRef:
        key: {{ .Values.secrets.data.MONGODB_URI }}
    - secretKey: JWT_ACCESS_SECRET
      remoteRef:
        key: {{ .Values.secrets.data.JWT_ACCESS_SECRET }}
    - secretKey: JWT_REFRESH_SECRET
      remoteRef:
        key: {{ .Values.secrets.data.JWT_REFRESH_SECRET }}
    - secretKey: REDIS_URL
      remoteRef:
        key: {{ .Values.secrets.data.REDIS_URL }}
    - secretKey: SES_FROM_EMAIL
      remoteRef:
        key: {{ .Values.secrets.data.SES_FROM_EMAIL }}
